name = "bg-remover-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "0c38849e184fbb6f0b9fef1616e36c2e"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "bg-remover-db"
database_id = "7ec3596b-849b-42f3-946b-20296fa5e027"

# 环境变量（非敏感）
[vars]
PAYPAL_BASE_URL = "https://api-m.sandbox.paypal.com"
PAYPAL_CLIENT_ID = "AUFLOnyj9frQbuKEFiUJpB-gUt3Wtrkk7AsKwfkK7vcu_1gb2aaLL4h2jTzCJve1X40143dKbYVTYnB-"
PAYPAL_PLAN_ID_BASIC = "P-3L415297LA876141DNHFDWDA"
PAYPAL_PLAN_ID_PRO = "P-6HF74783RV638001UNHFDWGY"

# 通过命令行设置 secret（不写入此文件）：
# wrangler secret put REMOVE_BG_API_KEY
# wrangler secret put PAYPAL_CLIENT_SECRET
